### ISSUE TITLE
Edge case failure

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_hdfs_reader#5]
Appears something isn't quite joining correctly. I believe this may be happening at the end of the file but still digging.

```
   failed to process { worker_id: '10.0.1.8__8',
      slice:
       { slice_id: '7acc3f0f-5872-4e69-af11-6e022ce0cfe1',
         request:
          { path: '/test/kstaken-2017.04/kteramac.local.4',
            offset: 12000000,
            length: 500000,
            total: 13843536 },
         slicer_id: 0,
         slicer_order: 25 },
      error: 'SyntaxError: Unexpected token {\n    at Object.parse (native)\n    at /Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:245:36\n    at Array.map (native)\n    at json_lines (/Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:245:17)\n    at /Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:111:24\n    at tryCatcher (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:580:21)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:580:21)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._resolveCallback (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:431:57)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:522:17)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._resolveCallback (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:431:57)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:522:17)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)' } and has slice state is marked as error
```

**Comment by kstaken** [comment]
Looks like there is a case where it can join two records together without a newline between them. When handed to json_lines it then fails to parse as JSON.

**Comment by kstaken** [comment]
Or maybe it's not an issue with joining lines but for some reason json_lines gets handed a record that is really two records that didn't get properly split apart.

```
{"ip":"178.83.125.19","userAgent":"Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 6.2; Trident/3.1; .NET CLR 4.6.40462.5)","url":"http://cornell.net","uuid":"caa3b457-986e-4647-89cf-4fbab40790a8","created":"2017-04-13T15:10:42.287-07:00","ipv6":"c11f:74dc:f626:4145:54b3:c82c:5867:5428","location":"-35.95216, 93.28547","bytes":1024254}{"ip":"177.14.220.48","userAgent":"Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.3; Trident/5.1; .NET CLR 1.3.80266.6)","url":"http://myrtle.com","uuid":"8ae01c4e-658d-4dab-8336-84501a736b02","created":"2017-04-13T15:10:45.484-07:00","ipv6":"9225:d951:19b2:02bf:5686:4eaa:e187:3a0e","location":"-22.71038, 79.57233","bytes":1308037}
```

**Comment by kstaken** [comment]
This was an issue in the source data. Will open a new ticket for improvement to the error handling.
