### ISSUE TITLE
Better handling of parsing errors

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_hdfs_reader#6]
If the source data isn't formatted correctly you receive an error similar to the following. The error is caught but it's not very clear what's causing it. I'm sure we can handle this more gracefully.

```
   failed to process { worker_id: '10.0.1.8__8',
      slice:
       { slice_id: '7acc3f0f-5872-4e69-af11-6e022ce0cfe1',
         request:
          { path: '/test/kstaken-2017.04/kteramac.local.4',
            offset: 12000000,
            length: 500000,
            total: 13843536 },
         slicer_id: 0,
         slicer_order: 25 },
      error: 'SyntaxError: Unexpected token {\n    at Object.parse (native)\n    at /Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:245:36\n    at Array.map (native)\n    at json_lines (/Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:245:17)\n    at /Users/kstaken/projects/opensource/teraslice_hdfs_reader/index.js:111:24\n    at tryCatcher (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:580:21)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:580:21)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._resolveCallback (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:431:57)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:522:17)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:691:18)\n    at Promise._fulfill (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:636:18)\n    at Promise._resolveCallback (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:431:57)\n    at Promise._settlePromiseFromHandler (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:522:17)\n    at Promise._settlePromise (/Users/kstaken/projects/opensource/terafoundation/node_modules/bluebird/js/release/promise.js:567:18)' } and has slice state is marked as error
```

**Comment by kstaken** [comment]
Current behavior is to just ignore the errors as data in HDFS is a bit wild and wooly. We may want to add an option in the future that controls the behavior on this so that you can specify tighter controls and get slice failures under some circumstances.
